AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Template for lambda
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # I don't know what this is
    Timeout: 3

Resources:
  ScrapeFunction:
    Type: AWS::Serverless::Function
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: './'
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      FunctionName: webScrapersProd
      # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      # Events:
